### ISSUE TITLE
Cannot add modules Debian 12

### ISSUE THREAD

**Issue by krauter** [AdityaGarg8/t2-ubuntu-repo#19]
New install on MacBook Pro 2019
 description: Laptop
    product: MacBookPro15,2
    vendor: Apple Inc.
    version: 1.0
    serial: C02Z2165LVDM
    width: 64 bits
    capabilities: smbios-3.3.0 dmi-3.3.0 smp vsyscall32
    configuration: boot=normal chassis=laptop family=MacBook Pro

$ uname -a
Linux xxxxxxx  6.14.7-1-t2-bookworm #1 SMP PREEMPT_DYNAMIC Sun May 18 09:44:09 UTC 2025 x86_64 GNU/Linux

Attempting to add any modules fails on compiling using the apt install method:

sudo apt install tiny-dfr
...stuff cut....
Do you want to continue? [Y/n] Y
Setting up linux-image-6.14.7-1-t2-bookworm (6.14.7-1) ...
dkms: running auto installation service for kernel 6.14.7-1-t2-bookworm.
Deprecated feature: REMAKE_INITRD (/var/lib/dkms/apple-ibridge/0.1/source/dkms.conf)
Deprecated feature: REMAKE_INITRD (/var/lib/dkms/applespi/0.1/source/dkms.conf)
Deprecated feature: REMAKE_INITRD (/etc/dkms/framework.conf)
Sign command: /lib/modules/6.14.7-1-t2-bookworm/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub
Deprecated feature: REMAKE_INITRD (/var/lib/dkms/apple-ibridge/0.1/source/dkms.conf)

Building module:
Cleaning build area...
make -j8 KERNELRELEASE=6.14.7-1-t2-bookworm...(bad exit status: 2)
Error! Bad return status for module build on kernel: 6.14.7-1-t2-bookworm (x86_64)
Consult /var/lib/dkms/apple-ibridge/0.1/build/make.log for more information.
Deprecated feature: REMAKE_INITRD (/etc/dkms/framework.conf)
Sign command: /lib/modules/6.14.7-1-t2-bookworm/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub
Deprecated feature: REMAKE_INITRD (/var/lib/dkms/applespi/0.1/source/dkms.conf

Attached error log - numerous compilation errors like:

apple-ib-tb.c:1293:19: error: initialization of ‘void (*)(struct platform_device *)’ from incompatible po
inter type ‘int (*)(struct platform_device *)’ [-Werror=incompatible-pointer-types]
 1293 |         .remove = appletb_platform_remove,
      |                   ^~~~~~~~~~~~~~~~~~~~~~

Am  I doing something wrong?

 

[error_compile.txt](https://github.com/user-attachments/files/20373511/error_compile.txt)

**Comment by krauter** [comment]
No drivers (that I know of?) were installed!  Installed Debian 12 from an iso on a stick - using external keyboard/mouse.  Maybe something got put on automagically.  I did TRY to install linux-t7 from your site - same errors as the above.  I can try starting from scratch.

**Comment by AdityaGarg8** [comment]
The logs clearly show you tried (maybe unknowingly) to install a driver for your Touchbar.

What is `dkms status`

**Comment by krauter** [comment]
You were correct.... I HAD tried to add drivers.  I reinstalled without t2-linux and all added fine however they seem to do nothing - i.e. keyboard, touchbar continue to be dead. 

ls updates/dkms
apfs.ko.xz           applesmc.ko.xz        bcm5974.ko.xz
apple-ibridge.ko.xz  apple-touchbar.ko.xz

sudo dkms status
applesmc-t2/0.1, 6.12.27-amd64, x86_64: installed (Original modules exist)
apple-touchbar/0.1, 6.12.27-amd64, x86_64: installed
bcm5974-t2/0.1, 6.12.27-amd64, x86_64: installed (Original modules exist)
linux-apfs-rw/0.3.13, 6.12.27-amd64, x86_64: installed

**Comment by AdityaGarg8** [comment]
> You were correct.... I HAD tried to add drivers. I reinstalled without t2-linux and all added fine however they seem to do nothing - i.e. keyboard, touchbar continue to be dead.
> 
> ls updates/dkms apfs.ko.xz applesmc.ko.xz bcm5974.ko.xz apple-ibridge.ko.xz apple-touchbar.ko.xz
> 
> sudo dkms status applesmc-t2/0.1, 6.12.27-amd64, x86_64: installed (Original modules exist) apple-touchbar/0.1, 6.12.27-amd64, x86_64: installed bcm5974-t2/0.1, 6.12.27-amd64, x86_64: installed (Original modules exist) linux-apfs-rw/0.3.13, 6.12.27-amd64, x86_64: installed

There are clear instructions to NOT use these if you are installing `linux-t2` in the readme.

Share `ls /usr/src` as well.

**Comment by krauter** [comment]
Found the glitch for most of it - keyboard/trackpad work well - forgot to install apple-bce module.  But still, touchbar is dead and not recognized.  The documentation is pretty lite for touchbar.  Seems to install fine - all files seem to be in correct places.  systemctl cannot start or enable the service (not sure it is supposed to start it anyhow) and running the command tiny-dfr as root or user yields: 
sudo tiny-dfr

thread main panicked at src/main.rs:538:43:
called `Result::unwrap()` on an `Err` value: No touchbar device found, attempted: [
    /dev/dri/card0: Device or resource busy (os error 16)
]
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by AdityaGarg8** [comment]
> Found the glitch for most of it - keyboard/trackpad work well - forgot to install apple-bce module. But still, touchbar is dead and not recognized. The documentation is pretty lite for touchbar. Seems to install fine - all files seem to be in correct places. systemctl cannot start or enable the service (not sure it is supposed to start it anyhow) and running the command tiny-dfr as root or user yields: sudo tiny-dfr
> 
> thread main panicked at src/main.rs:538:43: called `Result::unwrap()` on an `Err` value: No touchbar device found, attempted: [ /dev/dri/card0: Device or resource busy (os error 16) ] note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Why don't you just remove all these drivers and install `linux-t2`. Will make things easier.

**Comment by krauter** [comment]
As you sent that - I was already halfway through rebooting.  And YES - all seems to be working now.  I guess there are a few kernel flags set that modules alone cannot do.  Thanks for all your help - all works now.
